version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Allow up to 10 open pull requests for npm dependencies
    open-pull-requests-limit: 10
    # Specify labels for npm pull requests
    labels:
      - "dependencies"
      - "npm"
    # Set reviewers
    reviewers:
      - "pavlotsyhanok"
    # Group all updates together
    groups:
      dev-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Allow up to 5 open pull requests for GitHub Actions
    open-pull-requests-limit: 5
    # Specify labels for GitHub Actions pull requests
    labels:
      - "dependencies"
      - "github-actions"